env:
  global:
    - secure: "CZMUR6qI1/xwRlqBam8igRh7ttbC3rP5PrSyGuFtRaNfwszTub/H25S6u9svnc6iMtV2xnSnKWq9UxtIhqknSXrLYYqToac6+2fkCEqJXCjXC+nsnVD5wmFvq86MZ8BcPK8VHB5IH/hUgj0/eMW7aA0Nl3pwz/jyviLaEdGN2bzuYYaOXmiVkNaS/siCB1TnYV1/rNF0wMXXFqNA4O7UUDZluoLok0z5K0ASgDi8nk2QZpsqimhwbPM28ZOJ2wEJ0zhij7YDgFVFKx3iYS3y6ORIIhS1pZaPWEyPdfDmzAwk20ka8t3F3KGoimXNzmr2Ah1nEZ9cRTtUQbfDPPAjly/LqTU+sM5xv0H8w7OqPGQ4/aABncQd+3nl+HLrEh9jj6/uBb7YjCr8bngIi1850WN8WKrAt1VbflJfc+wODWmQ7hH77KyYDNwt0tiV+DXHdfXDqIefApuCOjU1IyOjG8jQtzW9bIYrjBjMbzaSIvG+IhvkZWhswrD2er4kVrVje4TzEnOn00je/ILmKtwgJj543X5OM2yqIz0NPVvIwKK+PJenAevxGgwnPOjXD8fQHKbohf3EM6r1kg1t+lnxhu6RsJgpjzqk6GERrx/SvALwN+gPlZQXjqNtT/pMztyVBrDV0OrfXuAEa4d3MmXqThI1Q4DNaaat9qQ3mi24t/s="
    - secure: "I4nQIA4BXhLHAz8etodXz7hdt09By6srS6FbKTnmId/WeFTtI2JXpj91pdExcPS1eZYyy9Olmy7EUeHGSqkgdpdy50zEA0a3Gljh82NlmPQV0wWFiYuCaJHsGas2swjkCvo0vJPhWzIzrKolYVI4uQQxm63UED70KoQFgKJHDUNECKhiBJWCM8tQN+NQo6p1fV1RBYvPDqlskhOzK0B5ui+GlDz/yYmgO4NRAcEG6EDQQ2idlvHfYGwsGcrrUdS2mLyAoU6bgvXKMV6vMf0mmdhXCChVNskrNp1Kb5DWUGN+Cmf1X3d2mqi3h3BUW49F5fWyxZOpmZaRk5jW+4YBsYCxZXjFlgBds10vLVxwqUAB4g+5q5ZudZxPR+6uFmer1WBbKfckjPcR7Xs0sWdSYl5aWkvGF3X5fTMxxStgDVn4uExJochjNNUR66Ofe366zg4a+0jccLaPRFp8bTFLFX5Ft/y3+hWZ/J3vOsmcR5DFog6eoyNo+ZZ6qfxI4u2EKNlhWBhN+BrTKlOm8tLkD37hyOOVy74JvW6WN5/q11O5pAJPTxZJifg1O9t621qrTGNZrq5U02w1O8hnWpf4RQb09r6S96MUgJWUtaC692oc+Pjj2ImY1n6xinFVEVeZQY0mKDlRnQFEyqkaGK6Fnw/0bwr+GDimU00bw7/DLXE="
language: python
sudo: required
services:
  - docker
python:
  - "3.5"
install:
  - "pyvenv .env"
  - ". .env/bin/activate"
  - "pip install -r requirements.txt"
script: pytest
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    echo "$REPO";
    echo "$COMMIT";
    echo "$TAG";
    echo "$TRAVIS_BUILD_NUMBER";
    fi